name: Build CI

concurrency:
  group: build
  cancel-in-progress: true

on: 
  - push

  # workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        python-version: ['3.10']
        os: [ windows-2019 ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      id: cp310
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        bash -c 'rm -rf "C:\hostedtoolcache\windows\Python\3.9.13"'
        bash -c 'rm -rf "C:\hostedtoolcache\windows\Python\3.7.9"'
        bazel clean --expunge
        pip install pybind11==2.10.4
        bash ./oss_scripts/configure.sh
        bash ./oss_scripts/run_build.sh
      env:
        LC_ALL: en_US.utf8
        PY_EXE: ${{ steps.cp310.outputs.python-path }}
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-wheel
        path: |
          *.whl
          dist
          dist/*.whl
